#!/usr/bin/env bash

target_file="$APPS_DIR/Notepad++/notepad++.exe"

if [ -f "$target_file" ]; then
  if [ -x "$target_file" ]; then
    "$target_file" $* & disown
    exit $?
  else
    echo "fail: proxied target is not executable: $target_file"
    exit 1
  fi
else
  echo "fail: proxied target is missing: $target_file"
  exit 2
fi
