#!/usr/bin/env bash

# yt-dlp has to be present
if ! command -v 'yt-dlp' 2>&1 >/dev/null; then
  echo 'fail: yt-dlp not installed'
  echo '  1. install via pacman: pacman -S yt-dlp'
  echo '  2. via github release: https://github.com/yt-dlp/yt-dlp/releases/'
  exit 1
fi

script_usage () {
  echo 'usage: ytmp4 <required: url> <optional: output file>'
  echo 'description: proxy script for yt-dlp to download an mp3 file'
  exit 1
}

url=$1
output_file=$2
extra_params=0

# allow optional parameters
# 1. without output file
if [ "$output_file" == "--" ]; then
  output_file=
  extra_params=1
fi

# 2. with output file
if [ "$3" == "--" ]; then
  extra_params=1
fi

if [ "$url" == "" ]; then
  script_usage
fi

if [ "$output_file" == "" ]; then
  if [ "$extra_params" == "1" ]; then
    yt-dlp -f "bestvideo+bestaudio/best" --recode mp4 "$url" $*
  else
    yt-dlp -f "bestvideo+bestaudio/best" --recode mp4 "$url"
  fi
else
  if [ "$extra_params" == "1" ]; then
    yt-dlp -f "bestvideo+bestaudio/best" --recode mp4 "$url" --output "$output_file" $*
  else
    yt-dlp -f "bestvideo+bestaudio/best" --recode mp4 "$url" --output "$output_file"
  fi
fi
